### ISSUE TITLE
Head.js keeps state of themself and it's appended after multiple iteration

### ISSUE THREAD

**Issue by razzededge** [Ariel-Rodriguez/react-amp-template#15]
This has happened to me after I rewrote the example app to allow generation of multiple files.
Basically what happened is that Head component when feeded with data (json prop in example) was appending each new data instead of overwriting props like the component Body does.

Basically this line 11. {state.elements} in https://github.com/Ariel-Rodriguez/react-amp-template/blob/master/src/Components/Head.jsx might be the source

**Comment by Ariel-Rodriguez** [comment]
Hi @razzededge  thanks for reporting this issue.
This happens because the Head's store is not flushed per execution.

A solution could be to add
```
state.elements.length = 0
```
Here https://github.com/Ariel-Rodriguez/react-amp-template/blob/master/src/store.js#L65

I don't have bandwidth to make the changes now, i'll try this weekend.
